apiVersion: v1
kind: ConfigMap
metadata:
  name: coworking-posgresql
data:
  DB_NAME: mydatabase
  DB_USER: myuser
  DB_HOST: postgresql-service
  DB_PORT: "5432"
---
apiVersion: v1
kind: Secret
metadata:
  name: coworking-secret
type: Opaque
data:
  db_password: bXlwYXNzd29yZA==
