apiVersion: v1
kind: Service
metadata:
  name: coworking
spec:
  type: LoadBalancer
  selector:
    service: coworking
  ports:
    - name: "5153"
      protocol: TCP
      port: 5153
      targetPort: 5153
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: coworking
  labels:
    name: coworking
spec:
  replicas: 1
  selector:
    matchLabels:
      service: coworking
  template:
    metadata:
      labels:
        service: coworking
    spec:
      containers:
        - name: coworking
          image: 433769608320.dkr.ecr.us-east-1.amazonaws.com/coworking:v0.0.1
          imagePullPolicy: IfNotPresent
          livenessProbe:
            httpGet:
              path: /health_check
              port: 5153
            initialDelaySeconds: 5
            timeoutSeconds: 2
          readinessProbe:
            httpGet:
              path: "/readiness_check"
              port: 5153
            initialDelaySeconds: 5
            timeoutSeconds: 5
          envFrom:
            - configMapRef:
                name: coworking-posgresql
          env:
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: coworking-secret
                  key: db_password
            - name: DB_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: coworking-posgresql
                  key: DB_USER
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: coworking-posgresql
                  key: DB_HOST
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: coworking-posgresql
                  key: DB_NAME
      restartPolicy: Always
